// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRT0dWJYvCDpPbgDU1nVsUwsBW_0YfL64',
    appId: '1:808110263198:web:022daf2881444c4260a48f',
    messagingSenderId: '808110263198',
    projectId: 'zenflow-9a8e0',
    authDomain: 'zenflow-9a8e0.firebaseapp.com',
    databaseURL: 'https://zenflow-9a8e0-default-rtdb.firebaseio.com',
    storageBucket: 'zenflow-9a8e0.firebasestorage.app',
    measurementId: 'G-83SHDTJB7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC10wo2wu0VsvARxwEtO9--7B1C5NZiJhc',
    appId: '1:808110263198:android:827119f6b418be3b60a48f',
    messagingSenderId: '808110263198',
    projectId: 'zenflow-9a8e0',
    databaseURL: 'https://zenflow-9a8e0-default-rtdb.firebaseio.com',
    storageBucket: 'zenflow-9a8e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMxzQqEsbNnIeA6Spc0keO0hiXkkzTvdk',
    appId: '1:808110263198:ios:4cf86772f962418260a48f',
    messagingSenderId: '808110263198',
    projectId: 'zenflow-9a8e0',
    databaseURL: 'https://zenflow-9a8e0-default-rtdb.firebaseio.com',
    storageBucket: 'zenflow-9a8e0.firebasestorage.app',
    iosBundleId: 'com.example.projetoBimestral',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMxzQqEsbNnIeA6Spc0keO0hiXkkzTvdk',
    appId: '1:808110263198:ios:4cf86772f962418260a48f',
    messagingSenderId: '808110263198',
    projectId: 'zenflow-9a8e0',
    databaseURL: 'https://zenflow-9a8e0-default-rtdb.firebaseio.com',
    storageBucket: 'zenflow-9a8e0.firebasestorage.app',
    iosBundleId: 'com.example.projetoBimestral',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRT0dWJYvCDpPbgDU1nVsUwsBW_0YfL64',
    appId: '1:808110263198:web:a5ae8b6bea3b305860a48f',
    messagingSenderId: '808110263198',
    projectId: 'zenflow-9a8e0',
    authDomain: 'zenflow-9a8e0.firebaseapp.com',
    databaseURL: 'https://zenflow-9a8e0-default-rtdb.firebaseio.com',
    storageBucket: 'zenflow-9a8e0.firebasestorage.app',
    measurementId: 'G-BVZ1VNVH64',
  );

}